In [1]:
%reload_ext autoreload
%autoreload 2

In [11]:
import json
from sklearn.model_selection import train_test_split
import pandas as pd

import sys
sys.path.append('/rhome/sawale/indus_traning/mlm-fine-tuning/notebooks/tdamm_analysis/')

from preprocess import preprocess_raw_json_training_file_mc_ml
# load text from tdamm

In [5]:
with open('/rhome/sawale/indus_traning/mlm-fine-tuning/notebooks/tdamm_analysis/tdamm_training_data_multi_labelled.json', 'r') as file:
        data = json.load(file)

df = preprocess_raw_json_training_file_mc_ml(data)
df.head()

,link,title,full_text,Active Galactic Nuclei,Binary Black Holes,Binary Neutron Stars,Binary Pulsars,Burst,Cataclysmic Variables,Compact Binary Inspiral,...,Stellar Mass,Stellar flares,Stochastic,SuperNovae,Supermassive,Supernova Remnants,Ultraviolet,White Dwarf Binaries,X-rays,non-TDAMM
0,https://science.nasa.gov/ems/12_gammarays/,Gamma Rays - NASA Science,Gamma Rays NASA Science Skip to main content M...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,https://science.nasa.gov/mission/burstcube/,BurstCube - NASA Science,BurstCube NASA Science Skip to main content Mi...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,https://science.nasa.gov/mission/fermi/,Fermi - NASA Science,Fermi NASA Science Skip to main content Missio...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,https://science.nasa.gov/mission/cgro/,CGRO - NASA Science,CGRO NASA Science Skip to main content Mission...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,https://science.nasa.gov/mission/integral/,INTEGRAL - NASA Science,INTEGRAL NASA Science Skip to main content Mis...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
len(train_df), len(test_df)

(408, 102)

In [9]:
train_df.rename(columns={"full_text": "text"}, inplace=True)
train_df = train_df[["text"]]
train_df.head()

                                                  text
310  Lunar Surface Electromagnetic Experiment LuSEE...
349  Physics of the Cosmos PhysCOS Skip navigation ...
485  Fast Radio Bursts facts and speculations Dunca...
137  Pulsar in a Box Reveals Surprising Picture of ...
497  Tibet Observatory Confirms Existence of Galact...

In [12]:
non_ej_text = pd.read_parquet('../data/parsed_sde_init_check_with_title.parquet')[["text"]].sample(train_df.shape[0])

mixed_text = pd.concat([train_df, non_ej_text]).sample(frac=1, random_state=42)

In [14]:
mixed_text.shape

(816, 1)

In [15]:

mixed_text.to_parquet('../data/mixed_tdamm_data.parquet')